(part "MCSJK-7I-8_00-18-30-60-B-30"
    (packageRef "MCSJK7I800183060B30")
    (interface
        (port "1" (symbPinId 1) (portName "CRYSTAL_1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "GND_1") (portType INOUT))
        (port "3" (symbPinId 3) (portName "CRYSTAL_2") (portType INOUT))
        (port "4" (symbPinId 4) (portName "GND_2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "171")
    (property "Manufacturer_Name" "Multicomp Pro")
    (property "Manufacturer_Part_Number" "MCSJK-7I-8.00-18-30-60-B-30")
    (property "Mouser_Part_Number" "")
    (property "Mouser_Price/Stock" "")
    (property "Arrow_Part_Number" "")
    (property "Arrow_Price/Stock" "")
    (property "Description" "MULTICOMP PRO - MCSJK-7I-8.00-18-30-60-B-30 - Crystal, 8 MHz, SMD, 5mm x 3.2mm, 30 ppm, 18 pF, 30 ppm")
    (property "Datasheet_Link" "https://www.farnell.com/datasheets/2864167.pdf")
    (property "symbolName1" "MCSJK-7I-8_00-18-30-60-B-30")
)
